version: '3'
volumes:
  mongodb:
services:
  chart-ui:
    build: ./client
    ports:
     - 3000:80
  chart-api:
    restart: always
    build: ./api
    ports:
     - 8080:8080
  db:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db