version: '3'
volumes:
  mongodb:
services:
  chart-api:
    stdin_open: true
    restart: always
    build: .
    ports:
     - 8080:8080
    volumes: 
      - '.:/usr/app'
      - '/usr/app/node_modules'
  db:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db