version: '3'
volumes:
  mongodb:
services: 
  chart-api:
    build: .
    ports:
     - 8080:8080

  db:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db